# Generated by Django 4.2.25 on 2026-01-01 22:18

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.marca_logo_path),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.producto_imagen_path),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.proveedor_imagen_path),
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField()),
                ('stock_minimo', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('atendida', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
            ],
            options={
                'db_table': 'alertas_stock',
            },
        ),
        migrations.AddConstraint(
            model_name='alertastock',
            constraint=models.UniqueConstraint(condition=models.Q(('atendida', False)), fields=('producto',), name='unique_alerta_stock_activa'),
        ),
    ]
