# Generated by Django 4.2.25 on 2026-01-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_marca_logo_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'permissions': [('puede_crear_movimiento', 'Puede crear movimientos de inventario'), ('puede_ver_movimientos', 'Puede ver movimientos de inventario')], 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
    ]
