# Generated by Django 4.2.25 on 2025-12-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_marca_fecha_creacion_alter_marca_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
    ]
