# Generated by Django 4.2.25 on 2025-12-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_marca_logo_alter_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('pieza', 'Pieza'), ('caja', 'Caja'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('m', 'Metro')], default='pieza', max_length=50),
        ),
    ]
