# Generated by Django 4.2.25 on 2026-01-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compra_fecha_actualizacion_compra_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
