# Generated by Django 4.2.25 on 2026-01-21 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categoria_codigo_producto_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
                'db_table': 'almacen',
            },
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.almacen'),
        ),
    ]
