# Generated by Django 4.2.25 on 2026-01-21 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_almacen_remove_inventario_ubicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='api.almacen'),
            preserve_default=False,
        ),
    ]
